# SMS Spam Classifier

#### This is an SMS Spam Classifier that predicts whether a text is spam or not and shows the confident score of that prediction

### To properly complete this project, we will divide this model into parts

## Part 1: Importing and Understading the Data

In [22]:
#we will first import the libraries

import re
import pandas as pd
import matplotlib as plt

In [5]:
#the we will load the csv dataset named collection

collection = pd.read_csv('SMSSpamCollection', sep='\t', names=['label', 'message'])

In [7]:
#always peep through the data to see how it looks like

collection.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#we also look at the shape to know 

collection.shape

(5572, 2)

In [ ]:
#counting the amount of ham and spam

collection['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

## Part 2: Cleaning the data

#### Now because the machine doesn't naturally understand nlp, will turn the text into an easier nlp model

In [20]:
#first we lowercase it

collection['message'] = collection['message'].str.lower()

In [ ]:
# we peep into the data to see what has changed

collection.head()

,label,message,message_lowercase
0,ham,"go until jurong point, crazy.. available only ...","go until jurong point, crazy.. available only ..."
1,ham,ok lar... joking wif u oni...,ok lar... joking wif u oni...
2,spam,free entry in 2 a wkly comp to win fa cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,u dun say so early hor... u c already then say...,u dun say so early hor... u c already then say...
4,ham,"nah i don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [26]:
# we create a function for easier cleaning, that is to remove punctuation and noise

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

#### the ^ in the sub means not

In [27]:
# then we apply it to the massages again

collection['message'] = collection['message'].apply(clean_text)

In [28]:
print(collection['message'])

0       go until jurong point crazy available only in ...
1                                 ok lar joking wif u oni
2       free entry in  a wkly comp to win fa cup final...
3             u dun say so early hor u c already then say
4       nah i dont think he goes to usf he lives aroun...
                              ...
5567    this is the nd time we have tried  contact u u...
5568                   will  b going to esplanade fr home
5569    pity  was in mood for that soany other suggest...
5570    the guy did some bitching but i acted like id ...
5571                            rofl its true to its name
Name: message, Length: 5572, dtype: str

## Part 3: Training and Testing the Model

### To train the model, we give the model training data and testing the data

#### To train the data we we will declare x and y (x meaning input and y meaning target)

In [29]:
# declaring the x and y

x = collection['message']

y = collection['label']

### For us to training both x and y, we will need to split the data

### For that to happen we  will use the scikit learn library

In [36]:
from sklearn.model_selection import train_test_split

In [44]:
# we use the train_test_split() to train and test the data

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

#### the stratify preserves the data after the split

In [45]:
# we look the shape of the training and testing for x 

print(x_train.shape)
print(x_test.shape)

(4457,)
(1115,)

In [46]:
# we look the shape of the training and testing for y

print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)

#### So it's like this:
#### x_train → training messages
#### y_train → answers for training messages

#### x_test  → unseen messages
#### y_test  → correct answers for those messages

In [47]:
print(y_train.value_counts())
print(y_test.value_counts())

label
ham     3859
spam     598
Name: count, dtype: int64
label
ham     966
spam    149
Name: count, dtype: int64